### ISSUE TITLE
shuffle-related random failures

### ISSUE THREAD

**Issue by crusaderky** [coiled/benchmarks#1010]
Tests are randomly failing with some frequency (maybe 1 in 10 times):

FAILED tests/benchmarks/test_join.py::test_set_index[1-p2p-True] - RuntimeError: P2P shuffling 1ae921940dd916ee7eeb387609c98fe2 failed during transfer phase
https://github.com/coiled/benchmarks/actions/runs/6262315429/job/17004221888

FAILED tests/benchmarks/test_join.py::test_set_index_on_uber_lyft[p2p-client0] - RuntimeError: shuffle_barrier failed during shuffle 9c5bfc79791693bcedf99f51bea8c3d8
https://github.com/coiled/benchmarks/actions/runs/6262315429/job/17004219737

CC @hendrikmakait

**Comment by crusaderky** [comment]
Two more examples:
https://github.com/coiled/benchmarks/actions/runs/6262315429/job/17012993085
https://github.com/coiled/benchmarks/actions/runs/6262315429/job/17012990170

**Comment by phofl** [comment]
This could be because of spot interruption. On my phone so can’t search for the cluster

**Comment by fjetter** [comment]
I was under the assumption that our benchmarks were not using spot, apparently false

**Comment by fjetter** [comment]
at least one of those failures is https://cloud.coiled.io/clusters/276019/information?account=dask-benchmarks which was due to a connection failure, not spot interruption

**Comment by hendrikmakait** [comment]
It looks like these not popping up anymore.
