### ISSUE TITLE
Where does this data live?

### ISSUE THREAD

**Issue by mrocklin** [coiled/benchmarks#1057]
I'd like to get numbers from TPC-H results.  For this I'd like to understand durations of each of the queries for different scales for different backends.  I'm curious, where is this data stored?

@milesgranger  or @crusaderky do either of you know this information?

**Comment by milesgranger** [comment]
If one runs the benchmarks locally, adding `--benchmarks` creates the local sqlite db in [this schema](https://github.com/coiled/benchmarks/blob/b8f0f0ee44fcd4d92c1e244a8b4c6c709ae3079f/benchmark_schema.py#L7)

**Comment by crusaderky** [comment]
both regular and A/B tests generate a benchmarks.db file in the github artifacts, which contains end-to-end runtime, mean and max memory usage of every test under every configuration. You can use A/B to compare different scales (e.g. 5 GB on 10 workers vs. 50 GB on 100 workers), different EC2 instances, etc.

Not sure if this answers your question.
