### ISSUE TITLE
TPCH - Where is scale 10?

### ISSUE THREAD

**Issue by mrocklin** [coiled/benchmarks#1066]
I'm seeing reference to `./tpch-data/scale10/` in the repository, but I'm not sure how to create/download it.  

I'd also like this as an option in cloud storage if someone wants to upload this to the right place (should be easy I hope)

@milesgranger I suspect that you have the most information here`

**Comment by milesgranger** [comment]
Yes sorry, maybe left over from debugging but found it helpful:

Download data:
- `aws s3 sync s3://coiled-runtime-ci/tpch_scale_10/ ./tpch-data/scale10/`

Shortcut the `coiled_function` fixture to not run on a cluster:  
- replace `functools.wraps(function)....` with `return function`

Then can run on the local data:
- `TPCH_SCALE=local python -m pytest -k duckdb --tpch-non-dask` for example.

**Comment by milesgranger** [comment]
If you want to keep this, I can add a PR to conditionally `return function` if the dataset is `local`.

**Comment by mrocklin** [comment]
I think I'll probably change around how we handle different scales generally. 

I'm curious though, how do I generate this data?

**Comment by mrocklin** [comment]
I think I'd like a world where ...

- We have a script or instructions for how to generate scale 10 and 100 locally
- We don't need to do spark nanosecond timing stuff (so probably we need to screw with scale 1000?)
- We have scale 10,000 in that same S3 bucket

@milesgranger are these things that you know how to do?  Or @phofl was this something that you set up and know more about?

**Comment by phofl** [comment]
The scripts to generate the data are here: https://github.com/pola-rs/tpch/tree/main/tpch-dbgen

You have to compile them and they need changes for ARM Macs. 

Generating scale 100 is relatively cpu expensive, I did this with coiled notebooks to reduce the time you have to wat.

**Comment by mrocklin** [comment]
OK, that's unpleasant.  Maybe we just point to that, but have instructions for people on how to download?

**Comment by mrocklin** [comment]
Can the scripts generate scale 1000 as well?  I'd like to avoid the nanosecond parquet thing.

**Comment by phofl** [comment]
Yeah sounds good. Setting this up is not too hard, but also far from trivial.

I wouldn't bother with re-creating. I would just read with Dask, cast the resolution and write again. Generating them takes quite a bit of time.

**Comment by mrocklin** [comment]
And storing as microseconds or milliseconds or whatever Spark accepts will work when routed through pandas and arrow?

**Comment by phofl** [comment]
Yep it should work if there aren't any bugs that I am not aware of

**Comment by phofl** [comment]
So, 10TB are here:

``s3://coiled-runtime-ci/tpch-scale-100000/`` (There is a 0 too many, sorry for that, have to fix that, but not today). Date is in ms, dask will still read in ns for me, so we are doing a copy there. Have to look into how we can avoid that.

The scale 1000 with date in ms is here:

``s3://coiled-runtime-ci/tpch-scale-1000-date/``

Same as above, dask will read in ns.

I repartitioned the data while dealing with them. Every partition has now 120MB. I am curious how this will affect performance.

**Comment by milesgranger** [comment]
I added https://github.com/coiled/benchmarks/pull/1106 for a more approachable way to generate (likely < scale 100) for users; no hard feelings if we don't want it.

I've also made a new folder on s3 `tpch/` which now has scales 1, 10, 100 (loading now), and 1000. If that seems okay, I can start moving the 10TB data there as well. So we have everything under one directory and common naming?

Now it's:
- s3://coiled-runtime-ci/tpch/scale-1
- s3://coiled-runtime-ci/tpch/scale-10
- s3://coiled-runtime-ci/tpch/scale-100
- s3://coiled-runtime-ci/tpch/scale-1000

**Comment by mrocklin** [comment]
I like the consistent and simple naming of the bucket and directories
