### ISSUE TITLE
Collect code from function rather than context

### ISSUE THREAD

**Issue by mrocklin** [coiled/benchmarks#1072]
When running TPC-H benchmarks I find that I don't get code samples from the polars/duckdb benchmarks.  This is a shame, I'd like to see the code that we run here.  (although to be clear, it's not a big deal).  

When thinking about it though, this makes sense.  We don't capture the code of the function itself, just the context from where it is called.  This makes sense for most of Dask because there are many different functions all being called for a given `compute` call.  It doesn't make sense to try to capture that code.  For `coiled.function` and `client.submit` more generally though, it might make sense to capture not just the context, but also the source code of the submitted function.  

I can imagine a world where Dask identifies this case, perhaps by conditioning on a computation not having any code samples, and there being only one function that is being called in all tasks of that computation.  We could then inspect the task, pick out the function, and share that code instead.  This is only one option for this problem; I suspect that there are others.  My guess is that this would add some code complexity, but in an isolated way, and that this would be relatively cheap (the checks are cheap).

No pressure or urgency.  This would be nice, but it's not a big deal.  I'm guessing that this is mostly a question for @fjetter and maybe @crusaderky .

**Comment by ntabris** [comment]
Not sure if this helps or not, but I'll mention that we have `coiled.span(cluster, callstack)` to capture code outside of the context of dask. This is currently used for `coiled run`:

https://github.com/coiled/platform/blob/e2755494a1c77184b58ce6e5da2d76610e66a2b5/python-api/coiled/cli/run.py#L472

**Comment by mrocklin** [comment]
Oh cool, so maybe we do the same thing for `coiled.function` generally?  We add the source-code of the function we're decorating?

I think it probably still makes sense to include the callstack if it's available.  We just want to add an extra internal layer.  Is this easy to do?

**Comment by crusaderky** [comment]
Not sure I understood the request here.
Are you asking that, when the user calls `client.submit`, you want dask to figure out if the passed callable is a generic library function (numpy, scipy, etc.) or user-defined code, and add a code snippet to the span only in the latter case?

How do you suggest telling them apart? Check if the path to the module contains `/site-packages/`?

**Comment by mrocklin** [comment]
That's not what I'm suggesting, no.  I'm suggesting that for Coiled function we include the code of the wrapped function in the code returned to Coiled, rather than just the context from which it is called.  From what I can tell, the suggestion from @ntabris should work well.

**Comment by mrocklin** [comment]
For broader motivation / context, if you take a look at any of the polars/duckdb tests they look like this:

https://cloud.coiled.io/clusters/292431/information?account=dask-benchmarks

<img width="1225" alt="Screenshot 2023-10-16 at 7 27 18 AM" src="https://github.com/coiled/benchmarks/assets/306380/028fe630-0f4f-4206-9dca-8509619b4fd4">

Similarly for Prefect we get only 

<img width="1208" alt="Screenshot 2023-10-16 at 7 27 43 AM" src="https://github.com/coiled/benchmarks/assets/306380/8101d937-21c8-48af-874a-43a0fab8eb14">

In these cases the context isn't very helpful, but we might be able to get some good insight from the function we're wrapping instead, whatever it is.

**Comment by mrocklin** [comment]
Oh sorry, the second example was for joblib.  Prefect jobs are similarly opaque though.
