### ISSUE TITLE
TPCH - Spark fails

### ISSUE THREAD

**Issue by mrocklin** [coiled/benchmarks#1074]
When I run from a freshly created environment as follows:

```
py.test --benchmark tests/benchmarks/tpch/test_pyspark.py::test_query_1 --tpch-non-dask
```

I get the following error:

```python-traceback
../../mambaforge/envs/test-env/lib/python3.11/site-packages/distributed/client.py:2823: in _run_on_scheduler
    raise exc.with_traceback(tb)
tests/benchmarks/tpch/test_pyspark.py:127: in _run_tpch
    return await asyncio.to_thread(_)
/opt/coiled/env/lib/python3.11/asyncio/threads.py:25: in to_thread
    ???
/opt/coiled/env/lib/python3.11/concurrent/futures/thread.py:58: in run
    ???
tests/benchmarks/tpch/test_pyspark.py:115: in _
    module.setup(spark)  # read spark tables query will select from
/opt/coiled/env/lib/python3.11/site-packages/tests/benchmarks/tpch/pyspark_queries/q1.py:28: in setup
    ???
/opt/coiled/env/lib/python3.11/site-packages/tests/benchmarks/tpch/pyspark_queries/utils.py:44: in read_parquet_spark
    ???
/opt/coiled/env/lib/python3.11/site-packages/pyspark/sql/readwriter.py:531: in parquet
    ???
/opt/coiled/env/lib/python3.11/site-packages/py4j/java_gateway.py:1322: in __call__
    ???
/opt/coiled/env/lib/python3.11/site-packages/pyspark/errors/exceptions/captured.py:169: in deco
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   Exception: Py4JJavaError('An error occurred while calling o41.parquet.\n', JavaObject id=o44)
```

https://cloud.coiled.io/clusters/292188/information?account=dask-benchmarks&tab=Logs&filterPattern=&computation=

@milesgranger does this work for you?

**Comment by mrocklin** [comment]
I'm also fine disregarding this for now and focusing on getting Spark working with SparkConnect.  I suspect that this will give us more accurate numbers anyway (it looks like today setup time is in the test)

**Comment by milesgranger** [comment]
Looks like the extended error includes:
> Caused by: com.amazonaws.SdkClientException: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY))
	at com.amazonaws.auth.EnvironmentVariableCredentialsProvider.getCredentials(EnvironmentVariableCredentialsProvider.java:50)
	at org.apache.hadoop.fs.s3a.AWSCredentialProviderList.getCredentials(AWSCredentialProviderList.java:177)
	... 44 more
	
This works for me with coiled==0.9.32, but fails after upgrading to coiled==1.1.0

Then when changing spark config to include the IAMInstanceCredentialsProvider it works for both versions:

```python
.config(
"spark.hadoop.fs.s3a.aws.credentials.provider", 
"com.amazonaws.auth.EnvironmentVariableCredentialsProvider,org.apache.hadoop.fs.s3a.auth.IAMInstanceCredentialsProvider",
 )
```

xref https://github.com/coiled/benchmarks/pull/1076
