### ISSUE TITLE
Report only shows data for TPC-H tests since 2023-10-14

### ISSUE THREAD

**Issue by hendrikmakait** [coiled/benchmarks#1097]
The reporting system only includes data for the TPC-H related tests since 2023-10-14. We stopped showing (persisting/recording?) data for all other tests.

<img width="1674" alt="Screenshot 2023-10-17 at 10 56 26" src="https://github.com/coiled/benchmarks/assets/2699097/a45cea21-b071-4a55-a411-33b7106a2bdd">

**Comment by phofl** [comment]
There are 2 different plots no, one before renaming the directory and one after

**Comment by hendrikmakait** [comment]
> There are 2 different plots no, one before renaming the directory and one after

That's #1098.

**Comment by hendrikmakait** [comment]
Closed as completed by #1101
