### ISSUE TITLE
test_join_big[1] deadlocks upon spot instance shutdown

### ISSUE THREAD

**Issue by crusaderky** [coiled/benchmarks#1228]
test_join_big[1] deadlocks very frequently.

I've now run it 40+ times, all on 2023.12.0, and and I've noticed a very high time correlation between deadlocks - e.g. either a whole suite of A/B tests is almost completely green, or it's almost completely red.

Example failed run:
- https://github.com/coiled/benchmarks/actions/runs/7200113744/job/19613325532
- s3://coiled-runtime-ci/test-scratch/cluster_dumps/join-94f47b9c/benchmarks.test_join.py.test_join_big[1].msgpack.gz
- https://cloud.coiled.io/clusters/333952/information?account=dask-benchmarks
- https://benchmarks-grafana.oss.coiledhq.com/d/GvbFsqKVk/coiled-cluster-metrics-basic?var-datasource=Benchmarks&var-account=dask-benchmarks&var-cluster=join-94f47b9c&var-cluster-id=333952&from=1702497314000&to=1702499727000&orgId=1

In the logs I read:
```
2023-12-13 19:59:36.6970
scheduler
distributed.shuffle._scheduler_plugin - WARNING - Shuffle 7903ec3183de28c82322c176e8e51223 restarted due to stimulus 'worker-close-gracefully-1702497576.496643

2023-12-13 19:59:36.7360
scheduler
distributed.core - ERROR - Exception while handling op shuffle_get
Traceback (most recent call last):
  File "/opt/coiled/env/lib/python3.9/site-packages/distributed/core.py", line 967, in _handle_comm
    result = handler(**msg)
  File "/opt/coiled/env/lib/python3.9/site-packages/distributed/shuffle/_scheduler_plugin.py", line 126, in get
    state = self.active_shuffles[id]
KeyError: '7903ec3183de28c82322c176e8e51223'
```
CC @fjetter @hendrikmakait

**Comment by fjetter** [comment]
@hendrikmakait do you have capacity to look into this?

**Comment by hendrikmakait** [comment]
I'll take a quick look into this. Depending on how far I get, I might have to prioritize this and other ongoing efforts.

**Comment by hendrikmakait** [comment]
https://github.com/dask/distributed/issues/8411

**Comment by hendrikmakait** [comment]
Closed as completed by https://github.com/dask/distributed/pull/8415
