### ISSUE TITLE
PR is blocked from merging if changes have been requested

### ISSUE THREAD

**Issue by hendrikmakait** [coiled/benchmarks#1295]
https://github.com/coiled/benchmarks/pull/1267 is currently blocked from merging because @fjetter has requested changes. Those changes have been addressed and I have approved the PR. Nonetheless, I cannot merge this approved PR. I suggest adjusting permissions such that approval by _any_ committer is enough to merge a PR.

**Comment by phofl** [comment]
I think that's a GitHub thing, we have the same in pandas. You can dismiss the review and move ahead with merging

**Comment by hendrikmakait** [comment]
> I think that's a GitHub thing, we have the same in pandas. You can dismiss the review and move ahead with merging

Thanks, @phofl. It looks like that's indeed what Github recommends (https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/dismissing-a-pull-request-review).
