### ISSUE TITLE
Don't use lambdas in query 9

### ISSUE THREAD

**Issue by phofl** [coiled/benchmarks#1296]
See https://github.com/coiled/benchmarks/pull/1277/files#r1469357583

Potentially other queries as well, lambdas block all optimizations.

Needs https://github.com/dask-contrib/dask-expr/issues/386 to work when chaining

**Comment by phofl** [comment]
cc @milesgranger https://github.com/dask-contrib/dask-expr/pull/821 should address the recursion error

**Comment by milesgranger** [comment]
Closed by https://github.com/coiled/benchmarks/pull/1299 and no other lambda functions exist in the dask queries as of now.
