### ISSUE TITLE
`duckdb=0.10.0` can't be installed from `conda-forge` for Windows

### ISSUE THREAD

**Issue by hendrikmakait** [coiled/benchmarks#1418]
There is currently no release for Windows because the build has failed: https://github.com/conda-forge/python-duckdb-feedstock/pull/93

This causes the `stability` tests to fail for Windows. Right now, I'd prefer having `duckdb=0.10.0` for TPC-H benchmarking over having working tests for Windows. I assume the problem will be resolved shortly.

**Comment by crusaderky** [comment]
Closing as we moved to pip
