### ISSUE TITLE
Set index regression

### ISSUE THREAD

**Issue by fjetter** [coiled/benchmarks#1463]
Haven't seen this pop up in another issue but browsing the data, this is a rather severe regression

![image](https://github.com/coiled/benchmarks/assets/8629629/5fd1ea45-f7aa-469a-9960-6770cf6898c6)

cc @phofl @hendrikmakait

**Comment by phofl** [comment]
Yikes and only for P2P, I'll take a look

**Comment by phofl** [comment]
I am confused, the dask and distributed commits are the same an the only thing that changed with dask-expr is https://github.com/dask/dask-expr/pull/971 which doesn't touch the code-paths of this benchmark.
Even more confusing, the first regression above was with exactly the same dask-expr run as the expected runtime before

**Comment by phofl** [comment]
performance is back to normal on latest run, closing here
