### ISSUE TITLE
How to create a dev environment to run tpch benchmarks?

### ISSUE THREAD

**Issue by mrocklin** [coiled/benchmarks#1493]
I'd like to make a development environment to run TPCH benchmarks locally on my macbook. Is there a set of environment files I should apply?

**Comment by mrocklin** [comment]
Pinging @crusaderky because I'm guessing that he has a good handle on the various environment files here (but I could be wrong)

**Comment by fjetter** [comment]
@milesgranger also did some work here recently. I think we should put this into the readme

**Comment by milesgranger** [comment]
This ought to be what you're after:
```
mamba create -n tmp python=3.9
mamba activate tmp
mamba env update -f ci/environment.yml
pip-compile ci/requirements-2tpch-non-dask.in
pip install -r ci/requirements-2tpch-non-dask.txt
```

I'll leave this open as a reminder to add to the README.

**Comment by crusaderky** [comment]
It's already in the README; not sure if there's anything actionable here?

https://github.com/coiled/benchmarks/blob/main/tests/tpch/README.md#setup
