### ISSUE TITLE
Stop maintaining `coiled-runtime` metapackage

### ISSUE THREAD

**Issue by jrbourbeau** [coiled/benchmarks#732]
_There have been some offline conversations / emails on this topic. I'm summarizing those here._ 

Today we have a lot of infrastructure / CI jobs around maintaining the `coiled-runtime` metapackage, but we're not really getting much value out of it anymore*. Coiled has moved away from `coiled-runtime` in favor of `package_sync` and we haven't really been actively maintain it. There are also some cases where the metapackage slows down our benchmarking efforts, where we do find lots of value (e.g. https://github.com/coiled/coiled-runtime/issues/650). 

If we're not getting value out of the metapackage, and in some cases it slows things down that we do care about, we should just drop the metapackage. Instead, we could just keep a set of environment files we use for benchmarking and are comfortable updating / patching as needed (e.g. `numba` doesn't have Python 3.11 support, so we just comment it out of the 3.11 environment file until it's available). This will let us clean things up a bit here, remove several CI jobs, and adapt more quickly on benchmarking (which is the main thing we care about at this point). 

*@crusaderky mentioned he finds being able to easily install a collection of tested packages useful, for example, when doing demos. He finds the metapackage useful for this purpose. He also said that pointing `mamba` at an environment file in this repo is an okay compromise.

**Comment by dchudz** [comment]
Would we continue pushing a docker image with the environment that the benchmarks use, or no? (I'm not saying we need to continue that, but various folks do find it useful.)

**Comment by jrbourbeau** [comment]
I don't think we've needed to touch that CI job in a long time, so we could probably keep it around if it's useful. Who is using those images?

**Comment by ntabris** [comment]
I currently use them when I want to boot an ARM cluster, but I think we'll have package and/or "create software environment" for ARM in next couple weeks, so I personally care less about multiarch images going away.

**Comment by jrbourbeau** [comment]
Sounds good. We can definitely coordinate to make sure things are smooth on you end. Is there anything else platform folks are using `coiled-runtime` for?

**Comment by crusaderky** [comment]
Another good reason for dropping the metapackage, besides numba:
xarray stopped supporting Python 3.8, while AFAIK we don't expect to drop it anytime soon.

So we need a Python 3.8-specific recipe that pins either an older version of xarray, or no xarray at all.

**Comment by mrocklin** [comment]
Is there anything else to do here?  It sounds like platform wants the docker image and James thinks that that's fine.  I think that we're good?

**Comment by jrbourbeau** [comment]
Closed via https://github.com/coiled/benchmarks/pull/793
